#!/bin/sh
# Rebuild src/font.js: GohuFont 14 (WTFPL, Nerd Fonts build) cut down to the
# characters hint labels use, embedded as base64 so no page CSP can block it.
set -e
cd "$(dirname "$0")/.."
SRC="${1:-$HOME/Library/Fonts/GohuFont14NerdFontMono-Regular.ttf}"
TMP="$(mktemp -d)/gohu14.ttf"
uvx --from fonttools pyftsubset "$SRC" \
  --text="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ;,./" \
  --layout-features='' --no-hinting --output-file="$TMP" 2>/dev/null
{
  echo '// Generated by tools/make-font.sh. GohuFont 14 by Hugo Chargois (WTFPL), subset.'
  echo '(globalThis.NaVIM ||= {}).fontData ='
  printf "  '%s';\n" "$(base64 < "$TMP" | tr -d '\n')"
} > src/font.js
echo "src/font.js: $(wc -c < src/font.js) bytes"
